name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build and Test
      run: dotnet build ProductCatalogService && dotnet test ProductCatalogService

    - name: Deploy
      # Add deployment steps here (e.g., deploying to AWS Lambda)
      run: echo "Deployment steps go here"
